# Generated by Django 6.0.1 on 2026-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentreminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
