# Generated by Django 6.0.1 on 2026-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_userprofile_age_userprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='document_size',
            field=models.FloatField(default=0.0, help_text='Total document size in MB'),
        ),
    ]
